// src/components/CBSEvents.tsx
import React from 'react';
import { CBSEvent } from '../state';

// Styles
import { Theme } from "@material-ui/core/styles/createMuiTheme";
import withStyles, { WithStyles } from "@material-ui/core/styles/withStyles";
import createStyles from "@material-ui/core/styles/createStyles";
import { FormControlLabel, Checkbox, Grid } from '@material-ui/core';
import { CourseData } from '../state/Course';

const styles = (theme: Theme) => createStyles({
  lessSpaceAbove: {
    marginTop: -theme.spacing(0.75),
  },
  secondaryText: {
    color: theme.palette.text.secondary,
  },
});

export interface Props extends WithStyles<typeof styles> {
  cbs: CourseData,
  events: CBSEvent[],
  onToggleEvent: (event: CBSEvent) => void,
}

export const CBSEvents = ({
  cbs,
  events,
  onToggleEvent,
  classes,
}: Props) => {
  const components = cbs.streams.map(s => s.component);
  const eventList = components.filter((c, i) => components.indexOf(c) === i);
  const eventCount = eventList.length;

  return (
    <Grid container spacing={0}>
      {eventList.map(eventName => (
        <Grid
          item
          xs={12}
          sm={6}
          md={eventCount === 4 ? 3 : 4}
          key={eventName}
        >
          <FormControlLabel
            control={
              <Checkbox
                checked={events.includes(eventName)}
                onChange={() => onToggleEvent(eventName)}
                value={eventName}
                data-cy={`cbs-event-${eventName}`}
              />
            }
            className={`${classes.secondaryText} ${classes.lessSpaceAbove}`}
            label={eventName}
          />
        </Grid>
      ))}
    </Grid>
  );
}

export default withStyles(styles)(CBSEvents);

// src/components/CBSEvents.vue
<template>
  <v-layout row wrap>
    <v-flex
      v-for="event in allEvents"
      :key="event.title"
      xs12 sm6 md3
    >
      <v-checkbox
        v-model="events"
        :value="event"
        :label="event"
        color="secondary"
        class="pb-2"
        hide-details
      >
      </v-checkbox>
    </v-flex>
  </v-layout>
</template>

<script>
  export default {
    computed: {
      events: {
        get () {
          return this.$store.state.events
        },
        set (newValue) {
          this.$store.commit('events', newValue)
        }
      },
      allEvents () {
        let data = this.$store.state.courseData.CBS
        if (!data) {
          return []
        } else {
          let streams = data.streams
          let components = streams.map(s => s.component)
          let unique = components.filter((c, i) => components.indexOf(c) === i)
          return unique
        }
      }
    }
  }
</script>
